# Generated by Django 4.1.1 on 2023-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('company_address', models.CharField(blank=True, max_length=256, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('company_email', models.CharField(blank=True, max_length=256, null=True)),
                ('company_website', models.CharField(blank=True, max_length=256, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
