# Generated by Django 4.2.1 on 2023-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscriptionmodel_planmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_address',
            new_name='company_country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='company_currency',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
