# Generated by Django 4.2.1 on 2023-05-27 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_company_address_user_company_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmodel',
            old_name='amount',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='subscriptionmodel',
            old_name='creator',
            new_name='endpoint_path',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='details',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='expirable',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='plan_enabed',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='subscription',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='disabled_plans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='industry_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='plan',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionmodel',
            name='subscribed_people',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
