# Generated by Django 4.2.1 on 2023-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_amount_planmodel_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionmodel',
            name='endpoint_path',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
