# Generated by Django 4.2.1 on 2023-11-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_planmodel_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amt', models.CharField(blank=True, max_length=512, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('mobile', models.CharField(blank=True, max_length=512, null=True)),
                ('card_number', models.CharField(blank=True, max_length=256, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=256, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
