# Generated by Django 4.2.1 on 2023-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_squaresubmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squaresubmodel',
            name='card_cvv',
        ),
        migrations.AddField(
            model_name='squaresubmodel',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='squaresubmodel',
            name='industry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
