# Generated by Django 4.2.1 on 2023-11-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_squaresubmodel_card_cvv_squaresubmodel_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squaresubmodel',
            old_name='group',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='squaresubmodel',
            name='plan',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
